### ISSUE TITLE
Meow and Org Mode

### ISSUE THREAD

**Issue by velppa** [meow-edit/meow#110]
Hey hey, thank you for the great package, I'm trying to switch to Meow from Evil after 10+ years of vimming, and it's the first time I'm seriously considering the switch, so kudos!

I'm using the default QWERTY layout with a few commands disabled (only meow-quit actually) as I don't need them.

In Org Mode Meow works very differently:
- After selection, like with `e` Meow doesn't show expansion labels and expansions either don't work or work inconsistnently, like `1` expands over several lines.
- Switching to Fundamental Mode, it works
- Switching back sometimes makes it working but not all the time.

Here's the screencast:
![meow-org-mode](https://user-images.githubusercontent.com/480160/145261908-65e3718a-c9a3-49b1-ac08-02cbaa9265f3.gif)

**Comment by DogLooksGood** [comment]
Expand should be disabled for modes listed in `meow-expand-exclude-mode-list`, by default, org and markdown. 
Because it's common to use variable pitch font, and different font sizes. Expand hints are represented as overlays, it will mess up the buffer. 

If you remove `org-mode` from the list, it will work, but
![](https://user-images.githubusercontent.com/11796018/144090190-d9806d67-7732-4e96-8e58-3bfcbba56fc1.gif)

So it is disabled by default.
Maybe we should just disable the hint, not the functionality.

**Comment by velppa** [comment]
Didn't know it was configurable, thank you, but if you say that it should always be disabled, then it's not the case, sometimes expansion works, but never the labels.

Yes, the expansion labels are not that important, but the functionality is needed as it enables lots of uses.
