### ISSUE TITLE
Meow-global-mode broken on emacs 26

### ISSUE THREAD

**Issue by eshrh** [meow-edit/meow#178]
(meow-global-mode 1) does not seem to work on emacs 26.3. I think it does not enter normal mode automatically.

**Comment by DogLooksGood** [comment]
Currently the oldest version supported is 27.2. I believe meow will not work on 27.1 neither. We have to fix issues by back porting more functions to make it work.

**Comment by DogLooksGood** [comment]
We have it mentioned here
https://github.com/meow-edit/meow/blob/master/GET_STARTED.org#dependencies

Yes, I also want to use meow with Emacs 26, because I have a few servers with ubuntu. I'm too lazy to compile Emacs 27. But at the moment, I'm working on #64, I'll open a discussion for my ideas later. It will be a big update I think(Although the overall usage should remain the same).

**Comment by DogLooksGood** [comment]
I've briefly investigated what is required to make it work with emacs 26.
1. define-minor-mode receives a different argument format
2. the `init-value` behavior is different in Emacs 26

**Comment by maddovr** [comment]
Perhaps this might help https://sr.ht/~pkal/compat/ ?

**Comment by DogLooksGood** [comment]
@maddovr Thanks for the information! But meow is a dependency free package.

**Comment by maddovr** [comment]
You can leave it dependency free for newer emacs versions, you're only adding a dependency for older emacsens. So your package could be adopted across more versions (granted, I'm not sure compat.el covers your usecase).

**Comment by eshrh** [comment]
too annoying, and i have no energy for this
