### ISSUE TITLE
Support emacs-28 `undo-redo`

### ISSUE THREAD

**Issue by ideasman42** [meow-edit/meow#214]
Emacs 28 adds redo, bound to `C-M-_`, could meow support this by default as it does for undo?

**Comment by DogLooksGood** [comment]
Meow doesn't have its own undo system. Just use the command `undo-redo`, it should work. The command `meow-undo` is just a simple wrapper that cancel the region before call the built-in `undo`.

**Comment by ideasman42** [comment]
Explaining my rationale for reporting this.

- meow looks really nice and worth learning.
- Undo & Redo are frequently accessed commands.
- Having a defacto-standard key binding for redo seems worth considering IMHO.

  Shift-U for example could be used for redo. Of course this is anecdotal / personal preference etc... but I've not once made use of undo-in-selection but I use redo many times a day. Undo-in-selection seems much more niche - people who use it could bind it to a key if they like.

Anyway, noting this as a suggestion for the default/proposed key-map, but think this can be closed if it's you would rather leave as-is.

**Comment by ideasman42** [comment]
Another option could be to call `undo-redo` after calling `negative-argument`, this seems in keeping with meow's design.

**Comment by eshrh** [comment]
I think at least wrapping redo should be implemented, even just for the sake of symmetry. I mean, meow-command.el is a 1.5k line file with wrappers for everything from C-d to to paredit style commands. I don't see why meow-redo shouldn't be included, it's a tiny addition.

As for your suggested keymap change, i'm more hesitant. 

1. Currently meow supports early 27, and I've actually been making effort to port it back to 26.
2. The shifted versions of keys shouldn't do opposite things, in my opinion, because it goes against the theme of other bindings, Of course, in my personal [bindings](https://github.com/eshrh/nyaatouch/blob/master/nyaatouch.el#L194) i don't respect this at all, but i think it has value in the defaults. Shift keys tend to do adjacent but less common versions of their nonshifted key. For example, hjkl vs HJKL, or ew vs EW, or y vs Y, or i vs I, This means that similar actions are (much, imo) easier to memorize, even if less efficient, common, or useful. I'm not saying this is a good choice in general, but changing this doesn't feel right to me given the other bindings. 

I think calling undo with a negative arg to call redo is actually a pretty interesting idea though, and i agree that it fits in with other bindings. 

Anyway, it's a single extra line in your config to bind any key in normal mode to the key sequence "C-M-_", calling whatever is bound to that. If meow-redo is wrapped around "C-M-_" i think this is about as elegant as it gets. For the record though, i totally use redo much more than undo in selection as well.

**Comment by ideasman42** [comment]
If it's important to support redo for emacs-26/27, the code for redo is quite minimal (undo-fu back-ported it to support older emacs versions).

See: https://gitlab.com/ideasman42/emacs-undo-fu/-/blob/f9c39c248cb965cd3c7cb3c8e15a4eee71921f8c/undo-fu.el#L73

**Comment by DogLooksGood** [comment]
Yeah, I didn't do it because I want to let meow support Emacrs 26.

**Comment by trev-dev** [comment]
I will bind something else myself, but +1 for `U` being redo later on.

**Comment by DogLooksGood** [comment]
I think this issue can be closed. The start key binding is just an example, I don't believe anyone using it without any modification. So just bind whatever commands you like.
