### ISSUE TITLE
Using meow + magit

### ISSUE THREAD

**Issue by trev-dev** [meow-edit/meow#229]
I am curious to know how people who are using Meow are also using magit. When I enter Magit, the meow keymap clashes.

I can't seem to find an easy way to use things like "discard hunk" (k) without first trying to figure out how to shut meow off.

**Comment by eshrh** [comment]
You have two options:
1. Press `?` to bring up the key prompt, and then press any key.
2. If you're using the qwerty keybind suggestions, then you can press `SPC j` and `SPC k` to call the original commands, since they're bound to `H-j` and `H-k` by default. If you're not, I'd suggest adding those two binds to your leader map with `meow-leader-define-key`.

**Comment by trev-dev** [comment]
These are great suggestions.  I didn't realize that `?` also meant that I could _use the keys_ in the help window. I also didn't know about `meow-leader-define-key` which is a good option. Thank you :)
