### ISSUE TITLE
Make some modes start in insert mode strangeness

### ISSUE THREAD

**Issue by dinkonin** [meow-edit/meow#260]
I'm trying to make vterm and eshell start in insert mode without success I tried
`(add-hook 'eshell-mode-hook #'meow-insert)` and `(add-hook 'eshell-mode-hook #'meow-insert-mode)`

The strangest thing is that when I try to debug it with `(debug-on-enter #'meow-insert)` it successfully switches modes after i close the debugger! 
I'm at a loss.

**Comment by DogLooksGood** [comment]
Well, actually it's not recommend to start in INSERT state, because in INSERT state, you don't have the full access to the leader. You have to take care of what your current state is after you switch window or whatever.

**Comment by dinkonin** [comment]
I understand that but in these terminal modes for me at least it makes sense to start in Insert and type commands with the leader just one <escape> away.

I've found a solution which works for me:
```
(defun +meow-force-insert ()
  (run-with-timer 0.01 nil #'meow-insert-mode))

(add-hook 'eshell-mode-hook #'+meow-force-insert)
```

But I still think Insert mode or as a matter of fact ANY mode, even custom ones should be a choosable option.

**Comment by eshrh** [comment]
Have you tried editing (or adding) the entry in `meow-mode-state-list`? I know its poorly named, but its meant for this kind of customization and recently as of #217 you can actually put any state (including insert, as you want, but even custom-defined states) as the value in the alist.

I'm fairly certain this works, because I actually use this for vterm-mode. Just add a new entry with 'add-to-list', it'll override the default entry for vterm (which chooses normal mode).

I just checked the customization document, and it says that only `normal` and `motion` are allowed. That's totally on me, I'll fix it. Sorry!
