### ISSUE TITLE
keypad only uses global map for `C-c` bindings

### ISSUE THREAD

**Issue by plattfot** [meow-edit/meow#275]
# Description
I have keybindings bound to `C-c` in multiple major modes but when pressing `SPC <key>` meow inserts the actual `<key>`, instead of running `C-c <key>` as I would expect. Reading the docs, this looks to be the default behavior when `C-c <key>` is unbound.

I would expect keypad to run `C-c <key>` as long as the `key` is not `x`, `c`, `h`, `m` or `g`.

# Repro

Here are steps to reproduce the issue. Commit dcc705b is the latest commit as of this writing.
```
cd /tmp
git clone https://github.com/meow-edit/meow.git
cd meow
git checkout dcc705b
emacs -Q --eval "(progn (require 'meow \"/tmp/meow/meow.el\") (meow-global-mode 1) (global-set-key (kbd \"C-c t\") #'emacs-version) (define-key lisp-interaction-mode-map (kbd \"C-c r\") #'emacs-version))"
```

Then hit `SPC t` and it will output the emacs version in the echo area. But hitting `SPC r` will insert `r` into the buffer. Hitting both `C-c t` and `C-c r` echoes the emacs version as expected.

**Comment by eshrh** [comment]
I agree, I'd expect the same.
In the most recent commit, I added an option such that when a key is undefined, we choose whether to insert the key, or just say it's undefined. There was some discussion in #271 about what the default behavior should be.

Here's what I'm thinking:
- change `meow-keypad-self-insert-undefined` to `meow-keypad-lookup-local-if-undefined`
- if a key is undefined, then lookup the key in the mode's map (like mentioned in this discussion, this would mean that if x is undefined, SPC x would call whatever was bound to x in that mode; this does not currently work)
- if this is bound to a real command, then call it
- if this is bound to self insert, then
  - if variable is t, then lookup the C-c + command using (local-key-binding), and call it if it exists, otherwise message undefined.
  - if variable is nil, no-op and message undefined.

What do you think about this?

also pinging @norris-young @fbergroth @DogLooksGood who were involved with this discussion earlier.

**Comment by plattfot** [comment]
I'm trying to wrap my head around this.
If I'm understanding you correctly. With what you suggest, meow's keypad and emacs' key bindings will behave different when a mode overloads a `C-c` keybinding. E.g.

```
emacs -Q --eval "(progn (require 'meow) (meow-global-mode 1) (global-set-key (kbd \"C-c t\") #'emacs-version) (define-key lisp-interaction-mode-map (kbd \"C-c t\") #'emacs-uptime))"
```
i.e.
```elisp
(require 'meow)
(meow-global-mode 1)
(global-set-key (kbd "C-c t") #'emacs-version)
(define-key lisp-interaction-mode-map (kbd "C-c t") #'emacs-uptime)
```

Hitting `C-c t` will call `emacs-uptime` but meow's keypad will still call `emacs-version` when hitting `SPC t`. As it priorities the global map over any local one.

To me that feels wrong. I would expect `C-c <key>` and `SPC <key>` to behave the same (ignoring  `x`, `m` etc). But I might be missing something obvious. :sweat_smile:

**Comment by eshrh** [comment]
Yeah... this is because `global-set-key`'ing the key `C-c t` puts `t` into the `mode-specific-map`, which happens to be the same place standard, top-level leader keys go, so there's no actual way to distinguish something defined via `global-set-key` and `meow-leader-define-key`. I'm open to considering changing this, but it would be a different discussion.

Anyway, maybe i should put this into code so we can try it.  check out my fork's master branch: https://github.com/eshrh/meow. The changes are implemented in the top commit.

**Comment by plattfot** [comment]
For me `(meow-leader-define-key <key> …)` and `(global-set-key (kbd "C-c <key>") …)` being equivalent is one thing I like about meow. So I wouldn't argue to change that. That makes it possible to reach key bindings defined by `meow-leader-define-key`when you are in the mini buffer. But yeah, let's leave that for now.

I tested your fork and it kind of works. My example above works. But it seems to not work with minor modes, here is a repro:

```elisp
(require 'meow)
(meow-global-mode 1)
(define-key lisp-interaction-mode-map (kbd "C-c s") #'emacs-version)

(defvar meow-issue-275-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-c t") #'emacs-uptime)
    map)
  "Custom keymap for `meow-issue-275-mode'.")
meow-issue-275-mode-map

(define-minor-mode meow-issue-275-mode
  "Meow issue #275:
\\{meow-issue-275-mode-map}"
  :version "0.0.1"
  :lighter nil
  :keymap meow-issue-275-mode-map
  nil)
(meow-issue-275-mode)
```
`SPC s` will work but not `SPC t`. Both `C-c s` and `C-c t` works as expected.

**Comment by eshrh** [comment]
You seem to be right. I just added another fallback for this.

**Comment by plattfot** [comment]
Works perfectly now! :tada:

> you're right again, there's some weird behavior in the local-key-bind function where if a function has no local binding, then it returns... 1, instead of nil like i expected rofl. Anyway, should be fixed now. I really appreciate your reproduction code!

No problem. I'm glad my repros was of use. And thank you for your quick response!

> I still want to wait for some of the people i mentioned earlier to weigh in before i merge these changes to meow-edit/master though.

No worries.

If someone is using [guix](https://guix.gnu.org/) to handle their emacs setup and want to test this out. You can use this:
```
guix shell emacs emacs-meow --with-git-url=emacs-meow=https://github.com/eshrh/meow.git --with-branch=emacs-meow=master -- emacs -Q
```
It made it really quick and easy for me to test this out.

**Comment by norris-young** [comment]
### Firstly, for weird behaviour of `local-key-binding`:
> you're right again, there's some weird behavior in the local-key-bind function where if a function has no local binding, then it returns... 1, instead of nil like i expected 🤣. Anyway, should be fixed now. I really appreciate your reproduction code!

`local-key-binding` uses `lookup-key`. As decribed in function `lookup-key`, it means key is **too long** because `C-c` prefix is not defined in `current-local-keymap`, and `1` character is at the front of KEY to reach a non-prefix key.

> lookup-key is a built-in function in ‘C source code’.
(lookup-key KEYMAP KEY &optional ACCEPT-DEFAULT)
Look up key sequence KEY in KEYMAP.  Return the definition.
A value of nil means undefined.  See doc of ‘define-key’
for kinds of definitions.
A number as value means KEY is "too long";
that is, characters or symbols in it except for the last one
fail to be a valid sequence of prefix characters in KEYMAP.
The number is how many characters at the front of KEY
it takes to reach a non-prefix key.

### Secondly, for the fallback to `C-c`:
A typical usage of keypad mode is binding `<key>` to `H-<key>` for the original command in motion state, which is described in the tutorial [https://github.com/meow-edit/meow/blob/master/TUTORIAL.org#motion](url).
This is also a commonly used configuration of my own as showing below, so it is my expected default behaviour instead of fallback to `C-c` you want nor the `self-insert-command` by default.
```
(meow-motion-overwrite-define-key
 '("j" . meow-next)
 '("k" . meow-prev)
 '("h" . meow-left)
 '("l" . meow-right)
 '("J" . meow-next-expand)
 '("K" . meow-prev-expand)
 '("H" . meow-left-expand)
 '("L" . meow-right-expand)
 '("n" . meow-search)
 '("v" . meow-visit)
 '(";" . meow-reverse))
(meow-leader-define-key
 ;; SPC j/k/h/l will run the original command in MOTION state.
 '("j" . "H-j")
 '("k" . "H-k")
 '("h" . "H-h")
 '("l" . "H-l")
 '("J" . "H-J")
 '("K" . "H-K")
 '("H" . "H-H")
 '("L" . "H-L")
 '("n" . "H-n")
 '("v" . "H-v")
 '(";" . "H-;"))

```
And, if we fallback to `C-c`, why is `C-c` instead of `C-x`, `C-h` or other `C-<key>` prefix defined by users(I defined `C-o`, `C-w`, `C-s`, `C-t`)? I don't want this fallback, since we can already use `SPC c <key>` for `C-c <key>`, which I think is clearer.

### Thirdly, for the key lookup of keypad mode, here's my understanding:
As described in elisp manual, the pseudo-lisp summary of how Emacs searches the active keymaps is:
```
(or (if overriding-terminal-local-map
        (FIND-IN overriding-terminal-local-map))
    (if overriding-local-map
        (FIND-IN overriding-local-map)
      (or (FIND-IN (get-char-property (point) 'keymap))
          (FIND-IN-ANY emulation-mode-map-alists)
          (FIND-IN-ANY minor-mode-overriding-map-alist)
          (FIND-IN-ANY minor-mode-map-alist)
          (if (get-text-property (point) 'local-map)
              (FIND-IN (get-char-property (point) 'local-map))
            (FIND-IN (current-local-map)))))
    (FIND-IN (current-global-map)))
```
meow keymap mode is implemented with `overriding-local-map` which will override local map as described by its name.
If I was right, **the searching method you want** is the pseudo-lisp below, which levels up the searching of the part that should be overrided by `overriding-local-map`:
```diff
 (or (if overriding-terminal-local-map
         (FIND-IN overriding-terminal-local-map))
     (if overriding-local-map
-        (FIND-IN overriding-local-map)
-      (or (FIND-IN (get-char-property (point) 'keymap))
-          (FIND-IN-ANY emulation-mode-map-alists)
-          (FIND-IN-ANY minor-mode-overriding-map-alist)
-          (FIND-IN-ANY minor-mode-map-alist)
-          (if (get-text-property (point) 'local-map)
-              (FIND-IN (get-char-property (point) 'local-map))
-            (FIND-IN (current-local-map)))))
+        (FIND-IN overriding-local-map))
+    (or (FIND-IN (get-char-property (point) 'keymap))
+        (FIND-IN-ANY emulation-mode-map-alists)
+        (FIND-IN-ANY minor-mode-overriding-map-alist)
+        (FIND-IN-ANY minor-mode-map-alist)
+        (if (get-text-property (point) 'local-map)
+            (FIND-IN (get-char-property (point) 'local-map))
+          (FIND-IN (current-local-map))))
     (FIND-IN (current-global-map)))
```
And In @eshrh implementation [https://github.com/eshrh/meow/commit/0d1eb2f79f19eff9b086a7b016a65771929600c5](url) :
```
(defun meow--keypad-lookup-key (keys)
  (let* ((local-binding (meow--local-key-bind keys))
         (cc-key (when (stringp keys) (concat "\C-c" keys)))
         (fallback-binding (when cc-key (meow--local-key-bind cc-key)))
         (minor-binding (when cc-key (cdar (minor-mode-key-binding cc-key))))
         (overriding-local-map meow--keypad-base-keymap)
         (keybind (key-binding keys)))
    (cl-find-if #'meow--if-keybinding-valid
                (list keybind local-binding fallback-binding minor-binding))))
```
This maybe equivalent to the following pseudo-lisp with a fallback of `C-c`:
```
(or (if overriding-terminal-local-map
        (FIND-IN overriding-terminal-local-map))
    (if overriding-local-map
        (FIND-IN overriding-local-map))
    (or (FIND-IN (current-global-map))
        (FIND-IN (current-local-map))
        (FIND-CCKEY-IN (current-local-map))
        (FIND-CCKEY-IN-ANY minor-mode-map-alist)))
```
In this case, the same key-binding in **global map takes precedence over major mode local map and minor mode map**.
I think this might not be what you want, isn't it? Because it is totally opposite to the default behaviour(**minor mode keymap takes precedence over major mode local map and global map**).

### At last, for a conclusion of my view:
1. I do not think `(meow-leader-define-key <key> …)` should be equivalent to `(global-set-key (kbd "C-c <key>") …)`. Fallling back to `C-c` isn't my expectation. In meow **motion** state, I use `SPC <key>` for `H-<key>` to call the **original command** on `<key>` of the major mode. This is my expected default behaviour instead of current `self-insert-command`. 
2.  I think we should follow the default searching method of Emacs. If you want to search the local keymap in keypad mode, maybe you can try to use `overriding-terminal-local-map` instead of `overriding-local-map` to implement keypad mode(I didn't read the c source code of `key-binding`, and I just think it might work referring to the pseudo-lisp in elisp manual).

Besides, I'm willing to hearing more about the original idea of keypad mode from @DogLooksGood .

**Comment by plattfot** [comment]
> And, if we fallback to C-c, why is C-c instead of C-x, C-h or other C-<key> prefix defined by users(I defined C-o, C-w, C-s, C-t)? I don't want this fallback, since we can already use SPC c <key> for C-c <key>, which I think is clearer.

I always assumed it was using `C-c` because that is the only emacs prefix reserved for the users. So keypad falling back to that make sense to me. It is also stated in the  [meow-tutor](https://github.com/meow-edit/meow/blob/master/meow-tutor.el#L578) that this is the behavior. Hence why I created this issue. But I see now that the [tutorial](https://github.com/meow-edit/meow/blob/master/TUTORIAL.org#keypad) state something different. I'm fine if the behavior is to map to `SPC <key>` -> `C-<key>` except for `m` and `g`.

**Comment by norris-young** [comment]
> > And, if we fallback to C-c, why is C-c instead of C-x, C-h or other C- prefix defined by users(I defined C-o, C-w, C-s, C-t)? I don't want this fallback, since we can already use SPC c  for C-c , which I think is clearer.
> 
> I always assumed it was using `C-c` because that is the only emacs prefix reserved for the users. So keypad falling back to that make sense to me. It is also stated in the [meow-tutor](https://github.com/meow-edit/meow/blob/master/meow-tutor.el#L578) that this is the behavior. Hence why I created this issue. But I see now that the [tutorial](https://github.com/meow-edit/meow/blob/master/TUTORIAL.org#keypad) state something different. I'm fine if the behavior is to map to `SPC <key>` -> `C-<key>` except for `m` and `g`.

It seems that translation from `SPC a` to `C-c a` was replaced from this patch https://github.com/meow-edit/meow/commit/845c4693ade5aa24715d3c0e4da678ca3fa98b51, so maybe meow-tutor was not updated?

**Comment by liushihao456** [comment]
It seems that ```(setq meow-keypad-leader-dispatch "C-c")``` works for me for the present.

**Comment by DogLooksGood** [comment]
@norris-young Great thanks for the information in details. 

The original idea of keypad is to simulating the input with modifiers. So you don't have to build your own leader-style keybindings. You can still define your key bindings in a vanilla Emacs way. 

But unfortunately, not all key bindings are friendly to keypad, for example: `C-x p` is only accessible via `SPC x SPC p`, which is inconvenient for such a frequently used command. So we introduce a quick access in keypad. A single leader key (SPC) can be used to quickly access a keymap or a key sequence. For example, you can set it to `C-x`, then `C-x p` becomes `SPC p`.
