### ISSUE TITLE
[Doom] `C-h` and `SPC h` are different prefixes

### ISSUE THREAD

**Issue by gagbo** [meow-edit/meow#337]
Hello,

I'm pretty sure it's been answered somehow already, but I didn't find any definitive, short, to the point, undisputed source of information for this. The closest is probably #242, but I'm not really sure.

My main problem is that, using Doom, `SPC h` and `C-h` lead to different things. 

C-h
![image](https://user-images.githubusercontent.com/10496163/194095737-0d38b4d2-51f8-49c5-874c-acf7c0077633.png)

SPC h
![image](https://user-images.githubusercontent.com/10496163/194095847-0f77822a-965a-4625-9452-06c843c61436.png)

Is there any documentation that explains why it is different and what I should do to fix this ? I thought, from reading the doc, that keypad would be a "raw" key translation scheme

All "keypad" doc says on github is that "hitting `SPC h` is like hitting `C-h`", which is like having a dead-end, since I don't know where I can find more information. I know emacs keymap resolution can be a mess most of the time (I made very specific `evil-collection` hooks for non standard keyboard layouts), I'd just like to know if there's something I can do to fix the matter.

For the record, Doom maps key to `help-map` [there](https://github.com/doomemacs/doomemacs/blob/1b1556c4766529cb75837d9d478be1d9bc491078/modules/config/default/config.el#L344-L421)

All my config is [here](https://git.sr.ht/~gagbo/doom-config/tree/meow/item/config-meow.el) if necessary, but I don't think I'm doing anything fancy really.

Thanks for the package and the work that's been put up until here,
Gerry

**Comment by aisamu** [comment]
I could only partially reproduce what the images show: `SPC h` seems to replace all group names with `+prefix`, but the list is otherwise identical.

The following was taken on a vanilla doom with the latest doom-meow and the "recommended" configuration (meow-edit/doom-meow@5fb355b57506148033eb2d7d8736a9d0ef0da06e)

#### `C-h` (works fine)

<img width="1917" alt="Screen Shot 2022-10-05 at 15 25 27" src="https://user-images.githubusercontent.com/431708/194136995-e2a12d9d-406f-49aa-a963-4b541a0a6bfe.png">

#### `SPC h` (all the purple entries became `+prefix`)

<img width="1920" alt="Screen Shot 2022-10-05 at 15 24 34" src="https://user-images.githubusercontent.com/431708/194137013-bd5642f9-d2a2-4864-830e-67a9015b4fb3.png">

I also tried shrinking the window to get multiple pages (as seen on your screenshots) with the same results

**Comment by aisamu** [comment]
`C-c` vs `SPC c` is more drastic and matches more of what you've described: 

#### `C-c`

<img width="830" alt="Screen Shot 2022-10-05 at 15 51 16" src="https://user-images.githubusercontent.com/431708/194139390-17aa2c58-4c43-430a-a762-5c4f21cf8bb6.png">

#### `SPC c`

<img width="716" alt="Screen Shot 2022-10-05 at 15 51 06" src="https://user-images.githubusercontent.com/431708/194139416-2ce530fa-8344-49ba-af6e-b2da086379b6.png">

The differences: 
* `SPC` is gone (reasonable, as it's a different thing on Keypad mode)
* `M-g - magit-file-dispatch` became `[ g` 
* `C-f - fold` is gone, and is being mapped to `forward-char` instead (and moves the cursor forward if you invoke it!)

Related: https://github.com/meow-edit/doom-meow/issues/5

**Comment by gagbo** [comment]
Are you using the "+leader" flag of the module ? It adds a lot of things I'm not sure I want, and at least until I have a rough idea of how mappings work, I'd rather start from a closer to bare emacs step, because when I break something I want to be able to at least reason about what's wrong

**Comment by gagbo** [comment]
Got my answer there : https://github.com/meow-edit/meow/discussions/226#discussioncomment-2656594

I need to press `SPC` again in order to make appear the "classic" keymaps. The crux is that even if which-key shows a bare `d`, hitting it really means `C-d`, so it shows this option instead.
