### ISSUE TITLE
Does meow-raise-sexp work?

### ISSUE THREAD

**Issue by jgarte** [meow-edit/meow#451]
I tried `meow-raise-sexp` but it was a no go.

Does it work?

**Comment by DogLooksGood** [comment]
Generally structure editing packages follow the convention, they bind `raise-sexp` to `M-r`. And `meow-raise-sexp` is a thin wrapper for that. It will disable current selection then call the underlying command via keybindings. These wrappers exist for old compatibility, now you don't have to use it. Since now you can map one keybinding to another, e.g. `("R" . "M-r")` will let you call the command on `M-r` with `R`.

Meow uses selection heavily, and in order to make users not have to care about whether there's a selection activated or not, we wrapped some commands for convenience in the past. But Meow has no opinion about which package to use.

**Comment by jgarte** [comment]
```lisp
(defun meow-raise-sexp ()
  "Raise sexp."
  (interactive)
  (meow--cancel-selection)
  (let ((bounds (bounds-of-thing-at-point 'sexp)))
    (when bounds
      (goto-char (car bounds))))
  (meow--execute-kbd-macro meow--kbd-raise-sexp))
  ```
