### ISSUE TITLE
Missing Commentary on meow-esc.el in Docstring

### ISSUE THREAD

**Issue by jgarte** [meow-edit/meow#510]
https://github.com/meow-edit/meow/blob/master/meow-esc.el#L16

Could we add a comment there?

I'm not sure what to put.

**Comment by DogLooksGood** [comment]
These code are copied from evil to make esc work in terminal.  :)

**Comment by jgarte** [comment]
What should we write for the module docstring explanation?

**Comment by DogLooksGood** [comment]
This module is used to patch the behavior of ESC key in terminal.

**Comment by jgarte** [comment]
Why was the patching required?

**Comment by eshrh** [comment]
It's because meta combos in the terminal send the exact same keycode as pressing ESC and then the key, which is why you can use ESC as meta in the terminal. This is problematic for evil and meow because esc is used while coding more frequently, if you press escape and then a key usually you don't want the meta combo. `meow-esc-delay` is the maximum time between ESC and the keypress that should be treated as a meta combo. If the time is longer than the delay, it's treated as pressing ESC and then the key separately
