### ISSUE TITLE
Is meow-delete intentionally removed?

### ISSUE THREAD

**Issue by igaryhe** [meow-edit/meow#73]
I noticed that in [commit dd39e17](https://github.com/meow-edit/meow/commit/dd39e17e431adb0dfdf5c182440c4951d307ac90) `meow-delete` is removed and aliased to `meow-C-d`. However, I think they don't perform the same. I use `meow-delete` pretty often and just found out I could no longer use it after I updated my `meow` package. Just would like to know if this is intentional and do we have any alternative function to it.

**Comment by DogLooksGood** [comment]
Yes, consider to use `meow-kill`.  `meow-kill` and original `meow-delete` are very similar, the main difference is update kill-ring or not. And `meow-kill` will not copy spaces-only content.

Since it's very common to have a selection in meow, it's better to have a command always delete one character. So it's recommended to have one command for kill region, and another for delete character.

**Comment by igaryhe** [comment]
Thanks for the explanation, this makes sense. It would be much better if
the project could have a changelog tracking all these "breaking" changes :D

**Comment by DogLooksGood** [comment]
Thanks, I'll add changelog after the documentation rework.
