### ISSUE TITLE
Error while using default theme

### ISSUE THREAD

**Issue by vohv** [meow-edit/meow#74]
![image](https://user-images.githubusercontent.com/28553596/141236689-01b00137-323d-422c-9b27-50460bea71f6.png)

**Comment by DogLooksGood** [comment]
Hi, the error should be fixed in 1bdf7c0cc07356c86c1cdf09eac0e9ba1bb6d426

However meow can't calculate a color if some face colors are unspecified. 
Follow faces should have a valid background or inherit a face which have valid background:
- region
- secondary-selection
- cursor
- default

Following face should have valid foreground or inherit a face which have valid foreground:
- default
