### ISSUE TITLE
Handle Ctrl+[

### ISSUE THREAD

**Issue by marad** [meow-edit/meow#83]
Hi I'm trying out the meow library and it seems cool!
Can I make `Ctrl+[` invoke the `meow-insert-exit` command like evil does?

Also - do you have any advice on how to move from vim bindings to meow?

**Comment by DogLooksGood** [comment]
Hi, this works for me
```
(when window-system
  (define-key input-decode-map (kbd "C-[") [control-bracketleft])
  (define-key meow-insert-state-keymap [control-bracketleft] 'meow-insert-exit))
```

For migration, 
1. Start from the Qwerty layout recommended [here](https://github.com/meow-edit/meow/blob/master/KEYBINDING_QWERTY.org). And yes, almost half of keys are different, since we are different modal editing system. It's just unavoidable. 
2. Tweaking the command layout based on your taste. 
3. Do NOT build a complex leader keymap, keep it simple. When you learn a new package, learn their default keybindings, using the default keymap with KEYPAD state. This help you to keep your configuration simple and maintainable.

My heavily configured Meow: https://github.com/DogLooksGood/dogEmacs/blob/master/elisp/init-modal.el

**Comment by DogLooksGood** [comment]
Now we have [Discussion](https://github.com/meow-edit/meow/discussions) for any questions. I'll close this issue for now.

**Comment by marad** [comment]
Thanks @DogLooksGood  for your response :)
