### ISSUE TITLE
meow-insert and move one character forwad

### ISSUE THREAD

**Issue by Inc0n** [meow-edit/meow#84]
Hi, I am coming from evil, is there any default way to enter `meow-insert` and one character forwad.

**Comment by krdzo** [comment]
Hi. I did something similar to that myself for `meow-appent`. It looks like this:
```
(defun kr-meow-append ()
  "Make `meow-append' behavior similar to evil-append."
  (unless (= (line-end-position) (point))
      (forward-char 1)))
(advice-add 'meow-append :after #'kr-meow-append)
```

Maybe there is a better way to do this but this works for me.

**Comment by DogLooksGood** [comment]
I have to explain for this.

`meow-insert` means insert at the beginning of region, and `meow-append` means append at the end of region. So when there's no region, insert and append will behave the same. The behavior is expected and reasonable.

It's simple to write your own function to move the cursor when no selection available. __BUT__, this doesn't get to the root of the problem.

For example, if you write your own `meow-append`. 

Press `a`, cursor stays
![image](https://user-images.githubusercontent.com/11796018/144613594-ab15c497-435d-4274-9522-d37edaa0b60a.png)

Press `a`, cursor moves
![image](https://user-images.githubusercontent.com/11796018/144613645-65e63044-24e2-4f95-8c6b-3cb9fe4783f1.png)

weird, doesn't it? 

In Vim, cursor is located on one character. In Emacs, cursor is located between two characters. (no matter the cursor shape)
In Kakoune, there's always a selection, with minimal width 1, but we can't do this in Emacs.

The only solution is to hack the cursor position, (like Evil does), I don't know what Evil does, but I have implemented one in Meow. 

```
;; Must set before enable `meow-global-mode`
(setq meow-use-cursor-position-hack t
      meow-use-enhanced-selection-effect t)  ;; optional, for visual effect

(meow-global-mode t)
```

__NOT RECOMMENDED__. I didn't even mention the feature in document. Since Meow is not Evil, I enjoy simplicity.

**Comment by Inc0n** [comment]
I think I am starting the see the difference between Evil and Meow now. These are not subtle changes. 
I am happy with the explanation so I will close this issue.
